<a href="https://colab.research.google.com/github/pkolenic/pytorch-video-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
 [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why Random tensores?

Random tensors are imported because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> load at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# Create a random tensor of size / shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2423, 0.4101, 0.2520, 0.4864],
        [0.9639, 0.9455, 0.6030, 0.0679],
        [0.8987, 0.3103, 0.7294, 0.7037]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zero and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensors of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensors-like

In [20]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Creating tensors like

In [21]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run itno with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%20the%20precision,used%20express%20a%20value.

In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor ( e.g. float32 or float16) - default float32
                               device=None, # what device is your tensor on - default 'cpu'
                               requires_grad=False # whether or not to track gradients with this tensor's operations - default 'False'
                               )
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.requires_grad


(tensor([3., 6., 9.]), torch.float32, device(type='cpu'), False)

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors (Attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [25]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8669, 0.1214, 0.1748, 0.6332],
        [0.3076, 0.8654, 0.0818, 0.1762],
        [0.9534, 0.9132, 0.7452, 0.6007]])

In [26]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Size of tensor: {some_tensor.size()} / Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.8669, 0.1214, 0.1748, 0.6332],
        [0.3076, 0.8654, 0.0818, 0.1762],
        [0.9534, 0.9132, 0.7452, 0.6007]])
Datatype of tensor: torch.float32
Size of tensor: torch.Size([3, 4]) / Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [27]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [28]:
# Multiple tensor by 10
tensor * 10

tensor([10, 20, 30])

In [29]:
tensor

tensor([1, 2, 3])

In [30]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [31]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [32]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication ( scaler multiplication)
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

For hands on learning try - http://matrixmultiplication.xyz/

There are two main rules that performing matrix multiplication needs to statisfy:
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` &rarr; `(2, 2)`
* `(3, 2) @ (2, 3)` &rarr; `(3, 3)`

In [33]:
torch.rand(3, 2) @ torch.rand(3,2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [34]:
# Element wiser multiplication
print(tensor,  '*',  tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [37]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1e+03 µs, sys: 16 µs, total: 1.02 ms
Wall time: 906 µs


tensor(14)

In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 210 µs, sys: 35 µs, total: 245 µs
Wall time: 217 µs


tensor(14)

In [39]:
%%time
tensor @ tensor

CPU times: user 180 µs, sys: 30 µs, total: 210 µs
Wall time: 328 µs


tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [40]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul and @)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [41]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a  **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [42]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [43]:
tensor_B.T, tensor_B.T.shape # transpose

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [44]:
# The matrix multiplication operation works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('output: \n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOputput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Oputput shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [45]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [46]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [47]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [48]:
# Find the mean - note: torch.mean() function requires a floating point datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [49]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [50]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [51]:
# Find the position in the tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
print(f'Min position is {x.argmin()} with a value of {x[x.argmin()]}')
# Find the position in the tensor that has the maximum value with argmax()
print(f'Max position is {x.argmax()} with a value of {x[x.argmax()]}')

Min position is 0 with a value of 1
Max position is 9 with a value of 91


## Reshaping, stacking, squeezing, and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape (alias of `View`, or at least currently is)
* View - Return a view of an input tensor of certain shape, but keep the same memory as the original tensor (By References)
* Stacking - combine multiple tenesor on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with the dimesions permuted (swapped) in a certain way

In [52]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
# Add an extra dimension
x_reshapped = x.reshape(1, 9)
x_reshapped, x_reshapped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
# Changing z changes x (because a view of a tensor shares the same memory of the original input)
z[0][0] = 5
z, x, x_reshapped

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [56]:
# Stack tensors on top of each other (dim=0)
x_stacked_dim0 = torch.stack([x, x, x, x], dim=0)
x_stacked_dim0, x_stacked_dim0.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [57]:
# Stack tensors beside each other (dim=0)
x_stacked_dim1 = torch.stack([x, x, x, x], dim=1)
x_stacked_dim1, x_stacked_dim1.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [58]:
# vstack is an alias for dim=0
x_vstacked = torch.vstack([x, x, x, x])
x_vstacked, x_vstacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [59]:
# hstack stacks within the same dimension
x_hstacked = torch.hstack([x, x, x, x])
x_hstacked, x_hstacked.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([36]))

In [60]:
# torch.squeeze() - removes all single dimensions from a target tensor
s = torch.tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(f'Previous tensor: {s}')
print(f'Previous shape: {s.shape}')

# Remove extra dimesnions from s
s_squeezed = s.squeeze()
print(f'\nNew tensor: {s_squeezed}')
print(f'New sahpe: {s_squeezed.shape}')

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New sahpe: torch.Size([9])


In [61]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target: {s_squeezed}')
print(f'Previous shape: {s_squeezed.shape}')

# Add an extra dimension with unsqueeze
s_unsqueezed = s_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {s_unsqueezed}')
print(f'New sahpe: {s_unsqueezed.shape}')

Previous target: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New sahpe: torch.Size([1, 9])


In [62]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similiar to indexing with NumPy

In [63]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [64]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [71]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1], x[0, 1, 1]

(tensor(5), tensor(5))

In [67]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [69]:
# Get all values of the 0th and 1st dimensions, but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [70]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [72]:
# Get index 0 or 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [73]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [78]:
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, Python has a functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarry)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [81]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
# Default NumPy data type
array.dtype

dtype('float64')

In [83]:
# Default Torch data type
torch.arange(1.0, 8.0).dtype

torch.float32

In [84]:
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [85]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [86]:
# Change the value of array, what will this do to the `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [87]:
# Tensor to NumPy array
tensor = torch.ones(7) # Default datatype is float32
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [88]:
numpy_tensor.dtype

dtype('float32')

In [89]:
# Change the tensor, what happens to the `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take the random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randonmness.

In [147]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2512, 0.6728, 0.1357, 0.7119],
        [0.8135, 0.6859, 0.2776, 0.6277],
        [0.1861, 0.2275, 0.6153, 0.8402]])
tensor([[0.7609, 0.9684, 0.9267, 0.4359],
        [0.0757, 0.2419, 0.6512, 0.1156],
        [0.0364, 0.3894, 0.1908, 0.9198]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [153]:
# Let's make some random but reproducabile tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Need to reset the seed to get the same results
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources on reproducibility:
- https://docs.pytorch.org/docs/stable/notes/randomness.html
- https://en.wikipedia.org/wiki/Random_seed


## Running tensors and PyTorch objects on the GPUS (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scences to make everything optimized.

### 1. Getting a GPU

1. Easiest - Use Google Colab getting a GPU for free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what options to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these are services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drives (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [1]:
!nvidia-smi

Mon Nov 10 20:09:13 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   59C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch


In [3]:
# Check for the GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if avaialble, else default to CPU

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [8]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensors back to the CPU

In [9]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')