<a href="https://colab.research.google.com/github/pkolenic/pytorch-video-learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00.PyTorch Fundamentals Exercises

## 1. Documentation reading
A big part of the deep learning (and learning to code in general) is getting familiar with documentation of a certain framework you're using.  We'll be using the PyTorch documentation a lot throughout the rest of the this course.  So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
- The documenation on [torch.Tensor](https://docs.pytorch.org/docs/stable/tensors.html#torch-tensor)
- The documentation on [torch.cuda](https://docs.pytorch.org/docs/main/notes/cuda.html#cuda-semantics)

In [2]:
# No code solution (reading)

## 2. Create random tensor with same `(7, 7)`.

In [24]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(7, 7)
tensor_A, tensor_A.shape

(tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
         [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
         [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
         [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
         [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
         [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
         [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]),
 torch.Size([7, 7]))

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with a shape `(1,7)` (hint: you may need to transpose the second tensor).

In [14]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(7, 7)

#Create another random tensor
tensor_B = torch.rand(1, 7)
tensor_B

# Perform matrix multiplication
product = torch.matmul(tensor_A,tensor_B.T)
product, product.shape

(tensor([[2.1391],
         [2.3548],
         [1.6001],
         [1.9384],
         [1.4356],
         [2.1416],
         [1.7684]]),
 torch.Size([7, 1]))

## 4. Set the random seed to `0` and do 2 & 3 over again
The output should be:

```
  (tensor([[1.8542],
          [1.9611],
          [2.2884],
          [3.0481],
          [1.7067],
          [2.5290],
          [1.7989]]), torch.Size([7, 1]))

In [16]:
# Import torch
import torch

# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

# Matrix multiple tensors
product = torch.matmul(tensor_A, tensor_B.T)
product, product.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

## 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
- If there is, set the GPU random seed to 1234.

In [4]:
# Import torch
import torch

# Set manual seed
RANDOM_SEED = 0

# Set random seed on the GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
if device == "cuda":
  torch.cuda.manual_seed(RANDOM_SEED)
else:
  torch.manual_seed(RANDOM_SEED)


cuda


## 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this).  Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).  The output should be something like:
```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [8]:
# Import torch
import torch

# Set manual seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

print(f'Device: {device}')
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

## 7. Perform a matrix multiplication on the sensors you created in 6 (again, you man have to adjust the shapes of one of the tesnors).
The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))


In [13]:
# Import torch
import torch

# Set manual seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

# Perform matmul on tensor_A and tensor_B
product = torch.matmul(tensor_A, tensor_B.T)
product, product.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

# 8. Find the maximum and minimum values of the output of 7.

In [18]:
# Import torch
import torch

# Set manual seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

# Perform matmul on tensor_A and tensor_B
product = torch.matmul(tensor_A, tensor_B.T)

# Find max
print(f'Max of Product: {product.max()}')

# Find min
print(f'Min of Product: {product.min()}')

Max of Product: 0.5617256760597229
Min of Product: 0.3647301495075226


## 9. Find the maximum and minimum index values of the output of 7.

In [19]:
# Import torch
import torch

# Set manual seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

# Perform matmul on tensor_A and tensor_B
product = torch.matmul(tensor_A, tensor_B.T)

# Find arg max
print(f'Max of Product: {product.argmax()}')

# Find arg min
print(f'Min of Product: {product.argmin()}')

Max of Product: 3
Min of Product: 0


## 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`.  Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:
```
  tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
  tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])

In [23]:
# Import torch
import torch

# Set manual seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
tensor_A = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_B = tensor_A.squeeze()

# Print out the tensors and their shapes
print(tensor_A, tensor_A.shape)
print(tensor_B, tensor_B.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
